name: Library System CI/CD Pipeline

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
    # ១. ទាញយកកូដពី GitHub Repository (Checkout)
    - name: Checkout Source Code
      uses: actions/checkout@v4

    # ២. រៀបចំបរិស្ថានម៉ាស៊ីន Python 3.12
    - name: Set up Python Environment
      uses: actions/setup-python@v5
      with:
        python-python: '3.12'

    # ៣. ដំឡើង Library ទាំងអស់ដែលមានក្នុង requirements.txt (Install dependencies)
    - name: Install Project Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # ៤. 🛠️ ដំណើរការរត់តេស្តកូដអូតូ (Run tests) ដែលយើងទើបតែបានបង្កើតជោគជ័យ
    - name: Run Automated Unit Tests
      run: |
        python -m pytest

    # ៥. ដំណើរការរុំកម្មវិធីទៅជា Docker Image (Build Docker image)
    - name: Build Docker Container Image
      run: |
        docker build -t library-app:latest .
